// design-sync prebuild — everything the converter needs that only this repo
// knows how to produce. Run it before package-build.mjs (cfg.buildCmd points
// here, so a re-sync picks it up automatically):
//
//   node .design-sync/prebuild.mjs
//
//   1. shims/public-assets.ts — /public imagery inlined as data URIs. The
//      next/image shim resolves site-absolute srcs through this map, so the
//      logo renders from the bundle instead of needing an origin to serve
//      /public. Videos are excluded; they are far past any sane inline size
//      and the components that use them are out of preview scope.
//   2. .cache/medirevs.css — a real Tailwind v4 compile of the site's own
//      globals.css (cfg.cssEntry). Utilities are scanned from the component
//      sources and the authored previews, so a class used only by a preview
//      is still in the shipped stylesheet.

import { createRequire } from "node:module";
import { readdirSync, readFileSync, mkdirSync, writeFileSync, statSync, existsSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");
const require = createRequire(join(REPO, "package.json"));

/* ── 1. public/ → data-URI map ──────────────────────────────────────── */

const MIME = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
};
// Comfortably clears the two logos (39KB / 23KB) and the video posters
// (18-55KB) while keeping anything unexpectedly large out of the bundle.
const MAX_INLINE = 128 * 1024;

function collect(dir, prefix, out) {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    const abs = join(dir, name);
    const st = statSync(abs);
    if (st.isDirectory()) {
      collect(abs, `${prefix}${name}/`, out);
      continue;
    }
    const mime = MIME[extname(name).toLowerCase()];
    if (!mime || st.size > MAX_INLINE) continue;
    out[`${prefix}${name}`] = `data:${mime};base64,${readFileSync(abs).toString("base64")}`;
  }
  return out;
}

const assets = collect(join(REPO, "public"), "/", {});
const bytes = Object.values(assets).reduce((n, v) => n + v.length, 0);

mkdirSync(join(HERE, "shims"), { recursive: true });
writeFileSync(
  join(HERE, "shims", "public-assets.ts"),
  `// GENERATED by .design-sync/prebuild.mjs — do not edit.\n` +
    `// /public imagery inlined so the bundle carries its own brand assets.\n` +
    `// ${Object.keys(assets).length} files, ${(bytes / 1024).toFixed(0)} KB encoded.\n\n` +
    `export const PUBLIC_ASSETS: Record<string, string> = ${JSON.stringify(assets, null, 2)};\n`,
);
console.error(
  `  public assets: ${Object.keys(assets).length} inlined (${(bytes / 1024).toFixed(0)} KB) — ` +
    Object.keys(assets).join(", "),
);

/* ── 2. Tailwind v4 compile ─────────────────────────────────────────── */

const postcss = require("postcss");
const tailwind = require("@tailwindcss/postcss");

const entry = join(HERE, "ds-entry.css");
const outFile = join(HERE, ".cache", "medirevs.css");
mkdirSync(dirname(outFile), { recursive: true });

const result = await postcss([tailwind()]).process(readFileSync(entry, "utf8"), {
  from: entry,
  to: outFile,
});
for (const w of result.warnings()) console.error(`  ! tailwind: ${w.toString()}`);
writeFileSync(outFile, result.css);
console.error(`  cssEntry: ${(result.css.length / 1024).toFixed(0)} KB → ${outFile.slice(REPO.length + 1)}`);
